# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables", "strikethrough"]
pygments:         true

# Permalinks
permalink: /:year/:month/:day/:title

# Setup
title: Tao Zhang
tagline: 'iOS, Karate, Cycling'
description: '<a href="https://twitter.com/ztpala" target="_blank">@ztpala</a>，关注<a href="/tag/#iOS">iOS开发</a>，<a href="/category/#空手道">空手道</a>以及<a href="/category/#自行车">自行车</a>。'
url: http://ztpala.com
domain: ztpala.com
twitterID: ztpala
disqusShortname: ztpala
timezone: America/New_York
subscribe: http://ztpala.com/atom.xml
exclude: [ README.md, newpost.rb ]

author:
  name:           'Tao Zhang'
  url:            https://twitter.com/ztpala

paginate:         5

github:
  repo:           https://github.com/pala/pala.github.com
  githubEditBaseURL: https://github.com/pala/pala.github.com/edit/master/
